### PR TITLE
fix for invalid use of path.join

### LINKED ISSUE #1360: There's a "capturedError: write EPIPE" and exception
When I run 
`oas capture --proxy http://localhost:8080 > traffic.har`
then I got an error
`» Proxy created. Redirect traffic you want to capture to https://localhost:8000
 help  Press [ Enter ] to finish capturing requests
⠏ 1 requests captured
⠋ 1 requests capturedError: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:917:11)
    at Socket._write (node:net:929:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Object.moveCursor (node:internal/readline/callbacks:85:17)
    at C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\commands\capture.js:247:84
    at step (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\commands\capture.js:56:23)
⠼ 1 requests captured`

I run this command:
`oas openapi.yml status --har traffic.har`
and I got this err:
`This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Malformed path '\v2\pet'
    at PathComponents.fromPath (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\index.js:106:19)
    at OperationQueries.matchPathPattern (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\queries.js:148:51)
    at OperationQueries.findPathPattern (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\queries.js:133:41)
    at SpecOperationDiffTraverser.<anonymous> (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\diffs\traversers.js:96:26)
    at step (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\diffs\traversers.js:24:23)
    at Object.next (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\diffs\traversers.js:5:53)
    at step (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\diffs\index.js:9:139)
    at Object.next (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\diffs\index.js:5:53)
    at Function.<anonymous> (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\streams\undocumented.js:123:88)
    at step (C:\Users\yongxin\scoop\persist\yarn\global\node_modules\@useoptic\openapi-cli\build\operations\streams\undocumented.js:47:23)`

How can I solve this problem?

Thanks

### PR DESCRIPTION
**Pull request by acunniffe**
## 🍗 Description
This fixes #1360 . `path.join` was being used to combine baseURLs and paths in the OpenAPI specifications -- however, on windows `join` uses `\` and for linux and URLs it used `/`. This is a platform agnostic way to join urls using a package we already had in the project 

## 📚 References
Replacing node's `path.join` with https://www.npmjs.com/package/url-join

## 👹 QA
[ ] Run it on Windows

### CODE REVIEW

File: projects/openapi-cli/src/operations/queries.ts [hunk 1]
```diff
@@ -1,18 +1,16 @@
...
-  OperationFacts,
-  OperationFact,
-  isFactVariant,
   FactVariants,
+  isFactVariant,
   OpenAPIV3,
   SpecFactsIterable,
 } from '../specs';
-import { Option, Some, None, Result, Ok, Err } from 'ts-results';
+import { Err, None, Ok, Option, Result, Some } from 'ts-results';
```
Comment (acunniffe) [inline projects/openapi-cli/src/operations/queries.ts:7]: lots of imports unused. cleaned up
